// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web.Data;

#nullable disable

namespace web.Migrations
{
    [DbContext(typeof(SkladisceContext))]
    [Migration("20221127181922_Fix2")]
    partial class Fix2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("web.Models.Izdelek", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sifra")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Izdelek", (string)null);
                });

            modelBuilder.Entity("web.Models.Skladisce", b =>
                {
                    b.Property<int>("SkladisceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkladisceId"), 1L, 1);

                    b.Property<int>("Cona")
                        .HasColumnType("int");

                    b.Property<int>("IzdelekID")
                        .HasColumnType("int");

                    b.Property<bool>("Zasedeno")
                        .HasColumnType("bit");

                    b.HasKey("SkladisceId");

                    b.HasIndex("IzdelekID");

                    b.ToTable("Skladisce", (string)null);
                });

            modelBuilder.Entity("web.Models.Skladisce", b =>
                {
                    b.HasOne("web.Models.Izdelek", "Izdelek")
                        .WithMany("Skladisca")
                        .HasForeignKey("IzdelekID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Izdelek");
                });

            modelBuilder.Entity("web.Models.Izdelek", b =>
                {
                    b.Navigation("Skladisca");
                });
#pragma warning restore 612, 618
        }
    }
}
